apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: data-summarization-agent
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/PROJECT_ID/data-summarization-agent:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          env:
            - name: PORT
              value: "8080"
  traffic:
    - percent: 100
      latestRevision: true